services:
  - type: static
    name: search-tool
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://search-tool-api.onrender.com
      - key: REACT_APP_DEBUG
        value: "false" 