version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LLM_PROVIDER=ollama
      - LLM_MODEL=mistral-7b-instruct-v0.2
      - LLM_TEMPERATURE=0.1
      - LLM_API_ENDPOINT=http://ollama:11434/api/generate
    depends_on:
      - ollama
    volumes:
      - ./backend/app:/app/app
    networks:
      - query-intent-network
    restart: unless-stopped

  # Ollama LLM service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - query-intent-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: serve

  # Optional - add frontend service if needed
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - query-intent-network
    restart: unless-stopped

networks:
  query-intent-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local 