name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        pytest
      env:
        APP_ENVIRONMENT: test
    
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Add deployment steps for your platform
    # For Render, you might use their Deploy Hook

services:
  # Backend API service
  - type: web
    name: search-comparisons-api
    env: python
    region: ohio
    plan: starter
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
      - key: ADS_API_TOKEN
        sync: false
      - key: SEMANTIC_SCHOLAR_API_KEY
        sync: false
      - key: WEB_OF_SCIENCE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://search-comparisons.onrender.com,https://search.sjarmak.ai
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend web application
  - type: web
    name: search-comparisons-web
    env: static
    region: ohio
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    nodeVersion: 18.17.1
    envVars:
      - key: REACT_APP_API_URL
        value: https://search-comparisons-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=0, no-cache, no-store, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
