name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        pytest
      env:
        APP_ENVIRONMENT: test
    
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Add deployment steps for your platform
    # For Render, you might use their Deploy Hook

services:
  - type: web
    name: search-comparisons-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LLM_PROVIDER
        value: ollama
      - key: LLM_MODEL_NAME
        value: qwen2:7b
      - key: LLM_TEMPERATURE
        value: 0.1
      - key: LLM_MAX_TOKENS
        value: 1024
      - key: LLM_API_ENDPOINT
        value: http://ollama:11434/api/generate
      - key: ADS_API_TOKEN
        sync: false
      - key: SOLR_URL
        value: https://api.adsabs.harvard.edu/v1/search/query
      - key: CORS_ORIGINS
        value: https://search-comparisons-frontend.onrender.com
      - key: ENVIRONMENT
        value: production
    depends_on:
      - ollama

  - type: web
    name: ollama
    image: ollama/ollama:latest
    env: docker
    startCommand: serve
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  - type: web
    name: search-comparisons-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://search-comparisons-backend.onrender.com
      - key: NODE_ENV
        value: production
