services:
  - type: web
    name: search-tool-api
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: relevancedb
          property: connectionString
      - key: FRONTEND_URL
        value: https://search-tool.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: LLM_ENABLED
        value: false
      - key: RATE_LIMIT_DELAY
        value: "2"
      - key: LOG_LEVEL
        value: INFO
      - key: ADS_API_KEY
        sync: false
      - key: WEB_OF_SCIENCE_API_KEY
        sync: false
      - key: QUEPID_API_KEY
        sync: false
      - key: QUEPID_API_URL
        sync: false

databases:
  - name: relevancedb
    databaseName: relevancedb
    user: relevancedb_user
    plan: free 