name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest
      env:
        APP_ENVIRONMENT: test


- name: Lint with ruff
  run: |
    pip install ruff
    ruff check .


- name: Run tests with coverage
  run: |
    pip install pytest pytest-cov
    pytest --cov=backend --cov-report=xml

- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v3
  with:
    file: ./coverage.xml

deploy-staging:
  if: github.ref == 'refs/heads/develop'
  # ...deployment steps for staging

deploy-production:
  if: github.ref == 'refs/heads/main'
  # ...deployment steps for production

        
  # If you're using Render for deployment
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
